@id=2bd00287-4cfe-4329-a3b0-927933874866

Put http://localhost:5051/breakfasts/{{id}}
Content-Type: application/json

{
  "name": "Vegan Sunshine",
  "description": "Vegan everything! Join us for a healthy breakfast..",
  "startDateTime": "2022-04-08T08:00:00",
  "endDateTime": "2022-04-08T11:00:00",
  "savory": [
    "Oatmeal",
    "Avocado Toast",
    "Omelette",
    "Salad"
  ],
  "sweet": [
    "Cookie"
  ]
}